// Generated by scripts/generate-chart-colors.ts. Do not edit by hand.

export const providerColors = {
  alibaba_cloud: "#6ac13c",
  anthropic: "#ff805d",
  cognition: "#d7ef39",
  cursor: "#f26898",
  deepseek: "#49c898",
  google: "#69c06a",
  meta: "#d6aa3c",
  moonshot_ai: "#abb73e",
  openai: "#3b9cff",
  xai: "#e58b69",
  z_ai: "#e58d32",
} as const;

export const openAiEffortColors = {
  none: "#4d86d1",
  low: "#3c84e8",
  medium: "#6589c0",
  high: "#3b9cff",
  xhigh: "#75a4ef",
  max: "#8db0ea",
} as const;
