import { readFile, rename, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import iwanthue from "iwanthue";
import { rgbHexToLab } from "iwanthue/helpers";

const providerIds = [
  "alibaba_cloud",
  "anthropic",
  "cognition",
  "cursor",
  "deepseek",
  "google",
  "meta",
  "moonshot_ai",
  "openai",
  "xai",
  "z_ai",
] as const;

// Provider colors are durable visual identities. New providers are reviewed and
// appended without asking the palette generator to recolor established series.
const pinnedProviderColors = {
  alibaba_cloud: "#6ac13c",
  anthropic: "#ff805d",
  cognition: "#d7ef39",
  cursor: "#f26898",
  deepseek: "#49c898",
  google: "#69c06a",
  meta: "#d6aa3c",
  moonshot_ai: "#abb73e",
  openai: "#3b9cff",
  xai: "#e58b69",
  z_ai: "#e58d32",
} as const;

const providerEntries = providerIds.map((providerId) => {
  const color = pinnedProviderColors[providerId];
  if (color === undefined) throw new Error(`Missing pinned color for ${providerId}.`);
  return [providerId, color] as const;
});

const effortSettings = ["none", "low", "medium", "high", "xhigh", "max"] as const;
const openAiEffortPalette = iwanthue(effortSettings.length, {
  attempts: 8,
  clustering: "k-means",
  colorSpace: { hmin: 265, hmax: 285, cmin: 30, cmax: 78, lmin: 50, lmax: 86 },
  distance: "cmc",
  originalColorsToExpand: [pinnedProviderColors.openai],
  quality: 80,
  // This pre-rename seed is stable chart data. Changing it would recolor every effort tier.
  seed: "codingchart/openai-effort/v1",
  ultraPrecision: true,
}).sort((left, right) => rgbHexToLab(left)[0] - rgbHexToLab(right)[0]);

const effortEntries = effortSettings.map((setting, index) => {
  const color = openAiEffortPalette[index];
  if (color === undefined) throw new Error(`Missing generated color for OpenAI ${setting}.`);
  return [setting, color] as const;
});

const serializeRecord = (name: string, entries: ReadonlyArray<readonly [string, string]>) => [
  `export const ${name} = {`,
  ...entries.map(([key, value]) => `  ${key}: "${value}",`),
  `} as const;`,
].join("\n");

const output = [
  "// Generated by scripts/generate-chart-colors.ts. Do not edit by hand.",
  serializeRecord("providerColors", providerEntries),
  serializeRecord("openAiEffortColors", effortEntries),
].join("\n\n") + "\n";

const targetUrl = new URL("../lib/chart-colors.generated.ts", import.meta.url);
const targetPath = fileURLToPath(targetUrl);
const checkOnly = Bun.argv.includes("--check");

if (checkOnly) {
  const current = await readFile(targetPath, "utf8").catch(() => "");
  if (current !== output) throw new Error("Generated chart colors are stale. Run `bun run colors:generate`.");
  console.info(`Validated ${providerEntries.length} provider colors and ${effortEntries.length} OpenAI effort shades.`);
} else {
  const temporaryPath = `${targetPath}.tmp`;
  await writeFile(temporaryPath, output, "utf8");
  await rename(temporaryPath, targetPath);
  console.info(`Wrote ${targetPath}.`);
}
