import { readFile, rename, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import iwanthue from "iwanthue";
import { labToHcl, rgbHexToLab } from "iwanthue/helpers";

const providerIds = [
  "alibaba_cloud",
  "anthropic",
  "cursor",
  "deepseek",
  "google",
  "meta",
  "moonshot_ai",
  "openai",
  "xai",
  "z_ai",
] as const;

const fixedProviderColors = {
  anthropic: "#ff805d",
  openai: "#3b9cff",
} as const;

const providerPalette = iwanthue(providerIds.length, {
  attempts: 10,
  clustering: "k-means",
  colorFilter: (_rgb, lab) => {
    const [hue, chroma, lightness] = labToHcl(lab);
    return (hue < 295 || hue > 345)
      && chroma >= 42
      && chroma <= 86
      && lightness >= 60
      && lightness <= 82;
  },
  distance: "compromise",
  originalColorsToExpand: Object.values(fixedProviderColors),
  quality: 80,
  seed: "codingchart/providers/v3-no-purple",
  ultraPrecision: false,
});

const fixedColors = new Set<string>(Object.values(fixedProviderColors));
const generatedProviderColors = providerPalette.filter((color) => !fixedColors.has(color));
let generatedIndex = 0;
const providerEntries = providerIds.map((providerId) => {
  if (providerId in fixedProviderColors) {
    return [providerId, fixedProviderColors[providerId as keyof typeof fixedProviderColors]] as const;
  }
  const color = generatedProviderColors[generatedIndex];
  generatedIndex += 1;
  if (color === undefined) throw new Error(`Missing generated color for ${providerId}.`);
  return [providerId, color] as const;
});

const effortSettings = ["none", "low", "medium", "high", "xhigh", "max"] as const;
const openAiEffortPalette = iwanthue(effortSettings.length, {
  attempts: 8,
  clustering: "k-means",
  colorSpace: { hmin: 265, hmax: 285, cmin: 30, cmax: 78, lmin: 50, lmax: 86 },
  distance: "cmc",
  originalColorsToExpand: [fixedProviderColors.openai],
  quality: 80,
  seed: "codingchart/openai-effort/v1",
  ultraPrecision: true,
}).sort((left, right) => rgbHexToLab(left)[0] - rgbHexToLab(right)[0]);

const effortEntries = effortSettings.map((setting, index) => {
  const color = openAiEffortPalette[index];
  if (color === undefined) throw new Error(`Missing generated color for OpenAI ${setting}.`);
  return [setting, color] as const;
});

const serializeRecord = (name: string, entries: ReadonlyArray<readonly [string, string]>) => [
  `export const ${name} = {`,
  ...entries.map(([key, value]) => `  ${key}: "${value}",`),
  `} as const;`,
].join("\n");

const output = [
  "// Generated by scripts/generate-chart-colors.ts. Do not edit by hand.",
  serializeRecord("providerColors", providerEntries),
  serializeRecord("openAiEffortColors", effortEntries),
].join("\n\n") + "\n";

const targetUrl = new URL("../lib/chart-colors.generated.ts", import.meta.url);
const targetPath = fileURLToPath(targetUrl);
const checkOnly = Bun.argv.includes("--check");

if (checkOnly) {
  const current = await readFile(targetPath, "utf8").catch(() => "");
  if (current !== output) throw new Error("Generated chart colors are stale. Run `bun run colors:generate`.");
  console.info(`Validated ${providerEntries.length} provider colors and ${effortEntries.length} OpenAI effort shades.`);
} else {
  const temporaryPath = `${targetPath}.tmp`;
  await writeFile(temporaryPath, output, "utf8");
  await rename(temporaryPath, targetPath);
  console.info(`Wrote ${targetPath}.`);
}
