import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { z } from "zod";

const root = resolve(import.meta.dir, "..");
const entry = z.object({
  id: z.string().regex(/^[a-z][a-z0-9-]{0,95}$/u), version: z.literal(1),
  family: z.string().regex(/^[a-z][a-z-]{0,63}$/u), question: z.string().min(1).max(256),
  unit: z.string().min(1).max(64), availability: z.enum(["existing-aggregate", "local-profile", "new-facts", "billing-evidence"]),
  implementationPhase: z.string().regex(/^(3|4|6|8|9|10)$/u),
  shipping: z.enum(["required", "source-conditional"]),
}).passthrough();

/** Project only the discovery vocabulary. Formula, proof and producer prose
 * stay in the source registry and never enter the interactive client bundle. */
export function projectMetricCatalog(value: unknown) {
  const document = z.object({ schemaVersion: z.literal(1), metrics: z.array(entry).length(241) }).passthrough().parse(value);
  if (new Set(document.metrics.map(metric => metric.id)).size !== document.metrics.length) throw new Error("metric_catalog_duplicate");
  return document.metrics.map(({ id, version, family, question, unit, availability, implementationPhase, shipping }) =>
    ({ id, version, family, question, unit, availability, implementationPhase, shipping }));
}

export async function generateMetricCatalog(check = false) {
  const projected = projectMetricCatalog(JSON.parse(await readFile(resolve(root, "verify/assurance/metrics.json"), "utf8")) as unknown);
  const families = [...new Set(projected.map(metric => metric.family))];
  const availability = ["existing-aggregate", "local-profile", "new-facts", "billing-evidence"];
  const shipping = ["required", "source-conditional"];
  const tuples = projected.map(metric => [metric.id, families.indexOf(metric.family), metric.question, metric.unit,
    availability.indexOf(metric.availability), metric.implementationPhase, shipping.indexOf(metric.shipping)]);
  const body = `// Generated by bun scripts/generate-metric-catalog.ts. Do not edit.\n`
    + `// Only discovery fields are shipped; the full assurance registry stays server/tool-side.\n`
    + `export const METRIC_CATALOG_PROJECTION_SHA256 = "${createHash("sha256").update(JSON.stringify(projected)).digest("hex")}";\n`
    + `export const MAX_METRIC_CATALOG_ROWS = 241;\nexport const MAX_METRIC_CATALOG_BYTES = 65_536;\n`
    + `export const METRIC_FAMILIES = ${JSON.stringify(families)} as const;\n`
    + `const availability = ${JSON.stringify(availability)} as const;\nconst shipping = ${JSON.stringify(shipping)} as const;\n`
    + `const rows = ${JSON.stringify(tuples, null, 0)} as const;\n`
    + `export type MetricCatalogEntry = Readonly<{ id: string; version: 1; family: typeof METRIC_FAMILIES[number]; question: string; unit: string; availability: typeof availability[number]; implementationPhase: string; shipping: typeof shipping[number] }>;\n`
    + `export const METRIC_CATALOG: readonly MetricCatalogEntry[] = Object.freeze(rows.map(([id, family, question, unit, state, implementationPhase, delivery]) => Object.freeze({ id, version: 1 as const, family: METRIC_FAMILIES[family], question, unit, availability: availability[state], implementationPhase, shipping: shipping[delivery] })));\n`;
  if (Buffer.byteLength(body) > 65_536) throw new Error("metric_catalog_projection_limit");
  const target = resolve(root, "lib/usage/metric-explorer-catalog.ts");
  if (check) {
    if (await readFile(target, "utf8") !== body) throw new Error("metric_catalog_projection_stale");
  } else await writeFile(target, body);
  return { rows: projected.length, bytes: Buffer.byteLength(body) };
}

if (import.meta.main) {
  try { console.log(JSON.stringify(await generateMetricCatalog(process.argv.includes("--check")))); }
  catch { console.error("metric_catalog_generation_failed"); process.exitCode = 1; }
}
